[build]
builder = "maven"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/login-auth-api-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/auth/login"
healthcheckTimeout = 60
